import Head from "next/head";
import PriceList from "../components/PriceList";
import Featured from "../components/Featured";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="styles.container">
      <Head>
        <title>Prath's Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PriceList />
    </div>
  );
}
